#!/bin/bash

# Only tested on Debian 8

# exit on error
set -e

# Add the MS Key
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Debian 8 mssql tools
curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Server component
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"

# Update our source list and install
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql17 mssql-tools unixodbc-dev mssql-server sqsh

echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.shell/S10env
source ~/.bashrc

# Improt the Keys for our tools
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Need to do this at the end [https://github.com/Microsoft/mssql-docker/issues/163]
echo "nb_NO.UTF-8 UTF-8" > /etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen

# Setup our server
/opt/mssql/bin/mssql-conf setup
